
// Additional medicines — appended to reach 200+
const EXTRA_MEDICINES=[
{name:"Pantoprazole 40mg",generic:"Pantoprazole",cat:"Digestive",uses:"GERD, peptic ulcer, acid reflux, Zollinger-Ellison syndrome",rx:true,img:""},
{name:"Esomeprazole",generic:"Esomeprazole",cat:"Digestive",uses:"GERD, stomach ulcers, H. pylori eradication",rx:true,img:""},
{name:"Rabeprazole",generic:"Rabeprazole Sodium",cat:"Digestive",uses:"Acid reflux, peptic ulcer, GERD",rx:true,img:""},
{name:"Simethicone",generic:"Simethicone",cat:"Digestive",uses:"Gas, bloating, flatulence, infant colic",rx:false,img:""},
{name:"Activated Charcoal",generic:"Activated Charcoal",cat:"Digestive",uses:"Poisoning, drug overdose, gas, bloating",rx:false,img:""},
{name:"Dicyclomine",generic:"Dicyclomine HCl",cat:"Digestive",uses:"IBS, stomach cramps, abdominal pain",rx:true,img:""},
{name:"Tinidazole",generic:"Tinidazole",cat:"Digestive",uses:"Bacterial and parasitic infections, giardia",rx:true,img:""},
{name:"Albendazole",generic:"Albendazole",cat:"Digestive",uses:"Worm infections, tapeworm, roundworm",rx:true,img:""},
{name:"Mebendazole",generic:"Mebendazole",cat:"Digestive",uses:"Pinworm, roundworm, hookworm infections",rx:false,img:""},
{name:"Zinc Sulphate Syrup",generic:"Zinc Sulphate",cat:"Digestive",uses:"Diarrhea in children, zinc deficiency",rx:false,img:""},
{name:"Cefpodoxime",generic:"Cefpodoxime Proxetil",cat:"Antibiotics",uses:"Respiratory, UTI, skin, ear infections",rx:true,img:""},
{name:"Cephalexin",generic:"Cephalexin",cat:"Antibiotics",uses:"Skin, respiratory, UTI, bone infections",rx:true,img:""},
{name:"Clindamycin",generic:"Clindamycin HCl",cat:"Antibiotics",uses:"Skin, dental, bone, pelvic infections",rx:true,img:""},
{name:"Nitrofurantoin",generic:"Nitrofurantoin",cat:"Antibiotics",uses:"Urinary tract infections",rx:true,img:""},
{name:"Trimethoprim-Sulfamethoxazole",generic:"Co-Trimoxazole",cat:"Antibiotics",uses:"UTI, respiratory, ear infections",rx:true,img:""},
{name:"Erythromycin",generic:"Erythromycin",cat:"Antibiotics",uses:"Respiratory, skin, STI infections",rx:true,img:""},
{name:"Ofloxacin",generic:"Ofloxacin",cat:"Antibiotics",uses:"UTI, respiratory, skin, eye infections",rx:true,img:""},
{name:"Norfloxacin",generic:"Norfloxacin",cat:"Antibiotics",uses:"UTI, diarrhea, gonorrhea",rx:true,img:""},
{name:"Amikacin",generic:"Amikacin Sulphate",cat:"Antibiotics",uses:"Severe bacterial infections, TB",rx:true,img:""},
{name:"Rifampicin",generic:"Rifampicin",cat:"Antibiotics",uses:"Tuberculosis, leprosy, meningitis prevention",rx:true,img:""},
{name:"Isoniazid",generic:"Isoniazid",cat:"Antibiotics",uses:"Tuberculosis treatment and prevention",rx:true,img:""},
{name:"Ethambutol",generic:"Ethambutol HCl",cat:"Antibiotics",uses:"Tuberculosis",rx:true,img:""},
{name:"Pyrazinamide",generic:"Pyrazinamide",cat:"Antibiotics",uses:"Tuberculosis",rx:true,img:""},
{name:"Fluconazole",generic:"Fluconazole",cat:"Antibiotics",uses:"Fungal infections, candidiasis, meningitis",rx:true,img:""},
{name:"Itraconazole",generic:"Itraconazole",cat:"Antibiotics",uses:"Fungal infections, nail fungus, aspergillosis",rx:true,img:""},
{name:"Lisinopril",generic:"Lisinopril",cat:"Heart & BP",uses:"High BP, heart failure, post heart attack",rx:true,img:""},
{name:"Enalapril",generic:"Enalapril Maleate",cat:"Heart & BP",uses:"High BP, heart failure, kidney protection",rx:true,img:""},
{name:"Valsartan",generic:"Valsartan",cat:"Heart & BP",uses:"High BP, heart failure, post heart attack",rx:true,img:""},
{name:"Olmesartan",generic:"Olmesartan Medoxomil",cat:"Heart & BP",uses:"Hypertension",rx:true,img:""},
{name:"Bisoprolol",generic:"Bisoprolol Fumarate",cat:"Heart & BP",uses:"High BP, heart failure, angina",rx:true,img:""},
{name:"Carvedilol",generic:"Carvedilol",cat:"Heart & BP",uses:"Heart failure, high BP, post heart attack",rx:true,img:""},
{name:"Digoxin",generic:"Digoxin",cat:"Heart & BP",uses:"Heart failure, atrial fibrillation",rx:true,img:""},
{name:"Furosemide",generic:"Furosemide",cat:"Heart & BP",uses:"Edema, heart failure, high BP",rx:true,img:""},
{name:"Spironolactone",generic:"Spironolactone",cat:"Heart & BP",uses:"Heart failure, edema, high BP, PCOS",rx:true,img:""},
{name:"Nitroglycerin",generic:"Glyceryl Trinitrate",cat:"Heart & BP",uses:"Angina, chest pain, heart failure",rx:true,img:""},
{name:"Warfarin",generic:"Warfarin Sodium",cat:"Heart & BP",uses:"Blood clot prevention, atrial fibrillation",rx:true,img:""},
{name:"Rivaroxaban",generic:"Rivaroxaban",cat:"Heart & BP",uses:"Blood clot prevention, DVT, stroke prevention",rx:true,img:""},
{name:"Apixaban",generic:"Apixaban",cat:"Heart & BP",uses:"Blood clot prevention, atrial fibrillation",rx:true,img:""},
{name:"Fenofibrate",generic:"Fenofibrate",cat:"Heart & BP",uses:"High triglycerides, cholesterol",rx:true,img:""},
{name:"Ezetimibe",generic:"Ezetimibe",cat:"Heart & BP",uses:"High cholesterol, combined with statins",rx:true,img:""},
{name:"Insulin Regular",generic:"Regular Insulin",cat:"Diabetes",uses:"Type 1 and Type 2 diabetes, hyperglycemia",rx:true,img:""},
{name:"Insulin NPH",generic:"Isophane Insulin",cat:"Diabetes",uses:"Type 1 and Type 2 diabetes",rx:true,img:""},
{name:"Canagliflozin",generic:"Canagliflozin",cat:"Diabetes",uses:"Type 2 diabetes, heart failure, kidney disease",rx:true,img:""},
{name:"Linagliptin",generic:"Linagliptin",cat:"Diabetes",uses:"Type 2 diabetes",rx:true,img:""},
{name:"Saxagliptin",generic:"Saxagliptin",cat:"Diabetes",uses:"Type 2 diabetes",rx:true,img:""},
{name:"Acarbose",generic:"Acarbose",cat:"Diabetes",uses:"Type 2 diabetes, post-meal blood sugar control",rx:true,img:""},
{name:"Repaglinide",generic:"Repaglinide",cat:"Diabetes",uses:"Type 2 diabetes, meal-time blood sugar",rx:true,img:""},
{name:"Gliclazide",generic:"Gliclazide",cat:"Diabetes",uses:"Type 2 diabetes",rx:true,img:""},
{name:"Prednisolone",generic:"Prednisolone",cat:"Allergy & Cold",uses:"Inflammation, allergies, asthma, autoimmune diseases",rx:true,img:""},
{name:"Dexamethasone",generic:"Dexamethasone",cat:"Allergy & Cold",uses:"Severe inflammation, allergies, COVID-19",rx:true,img:""},
{name:"Methylprednisolone",generic:"Methylprednisolone",cat:"Allergy & Cold",uses:"Severe allergies, inflammation, autoimmune",rx:true,img:""},
{name:"Budesonide Nasal Spray",generic:"Budesonide",cat:"Allergy & Cold",uses:"Allergic rhinitis, nasal polyps",rx:false,img:""},
{name:"Fluticasone Nasal Spray",generic:"Fluticasone Propionate",cat:"Allergy & Cold",uses:"Allergic rhinitis, nasal congestion",rx:false,img:""},
{name:"Oxymetazoline Spray",generic:"Oxymetazoline",cat:"Allergy & Cold",uses:"Nasal congestion, blocked nose",rx:false,img:""},
{name:"Vitamin A",generic:"Retinol",cat:"Vitamins",uses:"Eye health, immunity, skin, growth",rx:false,img:""},
{name:"Vitamin E",generic:"Tocopherol",cat:"Vitamins",uses:"Antioxidant, skin health, immunity",rx:false,img:""},
{name:"Vitamin K",generic:"Phytonadione",cat:"Vitamins",uses:"Blood clotting, bone health",rx:false,img:""},
{name:"Magnesium",generic:"Magnesium Oxide",cat:"Vitamins",uses:"Muscle cramps, constipation, migraine prevention",rx:false,img:""},
{name:"Potassium Chloride",generic:"Potassium Chloride",cat:"Vitamins",uses:"Potassium deficiency, muscle weakness",rx:false,img:""},
{name:"Biotin",generic:"Vitamin B7",cat:"Vitamins",uses:"Hair loss, nail health, metabolism",rx:false,img:""},
{name:"Coenzyme Q10",generic:"Ubiquinone",cat:"Vitamins",uses:"Heart health, energy, antioxidant",rx:false,img:""},
{name:"Glucosamine",generic:"Glucosamine Sulphate",cat:"Vitamins",uses:"Joint pain, osteoarthritis, cartilage health",rx:false,img:""},
{name:"Collagen Supplement",generic:"Hydrolyzed Collagen",cat:"Vitamins",uses:"Skin elasticity, joint health, bone strength",rx:false,img:""},
{name:"Probiotics",generic:"Lactobacillus + Bifidobacterium",cat:"Vitamins",uses:"Gut health, diarrhea, IBS, immunity",rx:false,img:""},
{name:"Acyclovir Cream",generic:"Acyclovir",cat:"Skin",uses:"Cold sores, herpes simplex, chickenpox",rx:false,img:""},
{name:"Permethrin Cream",generic:"Permethrin",cat:"Skin",uses:"Scabies, lice, skin parasites",rx:true,img:""},
{name:"Salicylic Acid Gel",generic:"Salicylic Acid",cat:"Skin",uses:"Acne, warts, psoriasis, dandruff",rx:false,img:""},
{name:"Benzoyl Peroxide",generic:"Benzoyl Peroxide",cat:"Skin",uses:"Acne, pimples, bacterial skin infections",rx:false,img:""},
{name:"Adapalene Gel",generic:"Adapalene",cat:"Skin",uses:"Acne, comedones, skin texture",rx:false,img:""},
{name:"Nystatin Cream",generic:"Nystatin",cat:"Skin",uses:"Fungal skin infections, candidiasis",rx:true,img:""},
{name:"Silver Sulfadiazine",generic:"Silver Sulfadiazine",cat:"Skin",uses:"Burns, wound infections",rx:true,img:""},
{name:"Urea Cream",generic:"Urea 10-40%",cat:"Skin",uses:"Dry skin, eczema, psoriasis, calluses",rx:false,img:""},
{name:"Montelukast + Levocetirizine",generic:"Montelukast + Levocetirizine",cat:"Allergy & Cold",uses:"Allergic rhinitis, urticaria, asthma",rx:true,img:""},
{name:"Tiotropium Inhaler",generic:"Tiotropium Bromide",cat:"Respiratory",uses:"COPD, chronic bronchitis, emphysema",rx:true,img:""},
{name:"Formoterol Inhaler",generic:"Formoterol Fumarate",cat:"Respiratory",uses:"Asthma, COPD, long-acting bronchodilator",rx:true,img:""},
{name:"Salmeterol Inhaler",generic:"Salmeterol",cat:"Respiratory",uses:"Asthma, COPD prevention",rx:true,img:""},
{name:"N-Acetylcysteine",generic:"N-Acetylcysteine",cat:"Respiratory",uses:"Mucus thinning, COPD, paracetamol overdose",rx:false,img:""},
{name:"Guaifenesin",generic:"Guaifenesin",cat:"Respiratory",uses:"Chest congestion, expectorant, cough",rx:false,img:""},
{name:"Codeine Syrup",generic:"Codeine Phosphate",cat:"Respiratory",uses:"Dry cough, mild to moderate pain",rx:true,img:""},
{name:"Latanoprost Eye Drops",generic:"Latanoprost",cat:"Eye & Ear",uses:"Glaucoma, high eye pressure",rx:true,img:""},
{name:"Timolol Eye Drops",generic:"Timolol Maleate",cat:"Eye & Ear",uses:"Glaucoma, high eye pressure",rx:true,img:""},
{name:"Ofloxacin Eye Drops",generic:"Ofloxacin",cat:"Eye & Ear",uses:"Bacterial eye infections, conjunctivitis",rx:true,img:""},
{name:"Sodium Cromoglicate Eye Drops",generic:"Sodium Cromoglicate",cat:"Eye & Ear",uses:"Allergic conjunctivitis, eye allergy",rx:false,img:""},
{name:"Ear Wax Softener",generic:"Carbamide Peroxide",cat:"Eye & Ear",uses:"Ear wax removal, blocked ears",rx:false,img:""},
{name:"Clotrimazole Ear Drops",generic:"Clotrimazole",cat:"Eye & Ear",uses:"Fungal ear infections, otomycosis",rx:true,img:""},
{name:"Quetiapine",generic:"Quetiapine Fumarate",cat:"Mental Health",uses:"Schizophrenia, bipolar disorder, depression",rx:true,img:""},
{name:"Olanzapine",generic:"Olanzapine",cat:"Mental Health",uses:"Schizophrenia, bipolar disorder",rx:true,img:""},
{name:"Risperidone",generic:"Risperidone",cat:"Mental Health",uses:"Schizophrenia, bipolar disorder, autism",rx:true,img:""},
{name:"Lithium Carbonate",generic:"Lithium Carbonate",cat:"Mental Health",uses:"Bipolar disorder, mania prevention",rx:true,img:""},
{name:"Venlafaxine",generic:"Venlafaxine HCl",cat:"Mental Health",uses:"Depression, anxiety, panic disorder",rx:true,img:""},
{name:"Duloxetine",generic:"Duloxetine HCl",cat:"Mental Health",uses:"Depression, anxiety, nerve pain, fibromyalgia",rx:true,img:""},
{name:"Mirtazapine",generic:"Mirtazapine",cat:"Mental Health",uses:"Depression, anxiety, insomnia",rx:true,img:""},
{name:"Buspirone",generic:"Buspirone HCl",cat:"Mental Health",uses:"Anxiety disorder, generalized anxiety",rx:true,img:""},
{name:"Propranolol",generic:"Propranolol HCl",cat:"Mental Health",uses:"Anxiety, tremors, performance anxiety, migraine",rx:true,img:""},
{name:"Methimazole",generic:"Methimazole",cat:"Thyroid",uses:"Hyperthyroidism, Graves disease",rx:true,img:""},
{name:"Propylthiouracil",generic:"Propylthiouracil",cat:"Thyroid",uses:"Hyperthyroidism, thyroid storm",rx:true,img:""},
{name:"Paracetamol Syrup",generic:"Acetaminophen Suspension",cat:"Pain & Fever",uses:"Fever and pain in children",rx:false,img:""},
{name:"Ibuprofen Syrup",generic:"Ibuprofen Suspension",cat:"Pain & Fever",uses:"Fever, pain, inflammation in children",rx:false,img:""},
{name:"Diclofenac Gel",generic:"Diclofenac Sodium",cat:"Pain & Fever",uses:"Local pain, joint pain, muscle pain",rx:false,img:""},
{name:"Methocarbamol",generic:"Methocarbamol",cat:"Pain & Fever",uses:"Muscle spasms, back pain, muscle relaxant",rx:true,img:""},
{name:"Cyclobenzaprine",generic:"Cyclobenzaprine HCl",cat:"Pain & Fever",uses:"Muscle spasms, back pain",rx:true,img:""},
{name:"Tizanidine",generic:"Tizanidine HCl",cat:"Pain & Fever",uses:"Muscle spasms, spasticity",rx:true,img:""},
{name:"Gabapentin",generic:"Gabapentin",cat:"Pain & Fever",uses:"Nerve pain, epilepsy, restless legs",rx:true,img:""},
{name:"Pregabalin",generic:"Pregabalin",cat:"Pain & Fever",uses:"Nerve pain, fibromyalgia, epilepsy, anxiety",rx:true,img:""},
{name:"Colchicine",generic:"Colchicine",cat:"Pain & Fever",uses:"Gout, familial Mediterranean fever",rx:true,img:""},
{name:"Allopurinol",generic:"Allopurinol",cat:"Pain & Fever",uses:"Gout prevention, high uric acid, kidney stones",rx:true,img:""},
{name:"Hydroxychloroquine",generic:"Hydroxychloroquine Sulphate",cat:"Pain & Fever",uses:"Malaria, rheumatoid arthritis, lupus",rx:true,img:""},
{name:"Chloroquine",generic:"Chloroquine Phosphate",cat:"Pain & Fever",uses:"Malaria treatment and prevention",rx:true,img:""},
{name:"Artemether-Lumefantrine",generic:"Artemether + Lumefantrine",cat:"Antibiotics",uses:"Malaria treatment",rx:true,img:""},
{name:"Doxylamine",generic:"Doxylamine Succinate",cat:"Mental Health",uses:"Insomnia, morning sickness in pregnancy",rx:false,img:""},
{name:"Promethazine",generic:"Promethazine HCl",cat:"Allergy & Cold",uses:"Allergies, nausea, motion sickness, sedation",rx:true,img:""},
{name:"Scopolamine Patch",generic:"Scopolamine",cat:"Allergy & Cold",uses:"Motion sickness, nausea, vomiting",rx:true,img:""},
{name:"Dimenhydrinate",generic:"Dimenhydrinate",cat:"Allergy & Cold",uses:"Motion sickness, nausea, vertigo",rx:false,img:""},
{name:"Betahistine",generic:"Betahistine HCl",cat:"Allergy & Cold",uses:"Vertigo, Meniere disease, tinnitus",rx:true,img:""},
{name:"Oxytocin",generic:"Oxytocin",cat:"Antibiotics",uses:"Labor induction, postpartum bleeding",rx:true,img:""},
{name:"Misoprostol",generic:"Misoprostol",cat:"Digestive",uses:"Stomach ulcers, labor induction, postpartum",rx:true,img:""},
{name:"Tranexamic Acid",generic:"Tranexamic Acid",cat:"First Aid",uses:"Heavy bleeding, menorrhagia, surgery",rx:true,img:""},
{name:"Vitamin K Injection",generic:"Phytonadione",cat:"First Aid",uses:"Bleeding disorders, newborn hemorrhage",rx:true,img:""},
{name:"Adrenaline Injection",generic:"Epinephrine",cat:"First Aid",uses:"Anaphylaxis, cardiac arrest, severe allergic reaction",rx:true,img:""},
{name:"Atropine",generic:"Atropine Sulphate",cat:"First Aid",uses:"Bradycardia, organophosphate poisoning, pre-anesthesia",rx:true,img:""},
{name:"Naloxone",generic:"Naloxone HCl",cat:"First Aid",uses:"Opioid overdose reversal",rx:true,img:""},
{name:"Glucose 25% Injection",generic:"Dextrose",cat:"First Aid",uses:"Hypoglycemia, energy supplement",rx:true,img:""},
{name:"Normal Saline",generic:"Sodium Chloride 0.9%",cat:"First Aid",uses:"Dehydration, wound cleaning, IV fluid",rx:false,img:""},
{name:"Ringer Lactate",generic:"Lactated Ringer Solution",cat:"First Aid",uses:"Dehydration, burns, surgery fluid replacement",rx:true,img:""}
];

// Merge with main array
if(typeof MEDICINES !== 'undefined'){
  MEDICINES.push(...EXTRA_MEDICINES);
  // Re-render after merge
  if(typeof renderResults === 'function') renderResults();
  if(typeof renderChips === 'function') renderChips();
}
